# Generated by Django 3.2 on 2021-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_socialicon_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='icon',
            field=models.CharField(max_length=255),
        ),
    ]
