# Generated by Django 3.2 on 2021-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_website_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
