# Generated by Django 3.2 on 2021-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210508_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description_newletter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
