# Generated by Django 3.2 on 2021-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_website_description_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.RenameField(
            model_name='socialicon',
            old_name='lien',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.FileField(upload_to='About_file'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='picture',
            field=models.FileField(upload_to='Banner_file'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.FileField(upload_to='Team_file'),
        ),
    ]
