# Generated by Django 3.2 on 2021-05-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefit',
            new_name='Prestation',
        ),
        migrations.AlterModelOptions(
            name='prestation',
            options={'verbose_name': 'Prestation', 'verbose_name_plural': 'Prestations'},
        ),
    ]
