# Generated by Django 3.2 on 2021-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210510_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantage',
            old_name='label',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='advantage',
            old_name='label_activate',
            new_name='title_activate',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='label',
            new_name='marque',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='title_label',
        ),
        migrations.AddField(
            model_name='pack',
            name='title_marque',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
