# Generated by Django 3.2 on 2021-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210510_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='title_marque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
