# Generated by Django 3.2 on 2021-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_pack_title_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='picture',
            field=models.FileField(upload_to='Prestation_file'),
        ),
    ]
