# Generated by Django 3.2 on 2021-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(upload_to='', verbose_name='Partner_file'),
        ),
        migrations.AlterField(
            model_name='pictureproject',
            name='picture',
            field=models.FileField(upload_to='PictureProject_file'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.FileField(upload_to='Testimonial_file'),
        ),
    ]
